### ISSUE TITLE
Installed but how do you configure?

### ISSUE THREAD

**Issue by Nylle8** [Kaltharos/RPGMods#17]
Tried installing this but it didn't work. Can you tell me what goes on the server and what goes client side? Thanks.

_Originally posted by @Nylle8 in https://github.com/Kaltharos/RPGMods/discussions/16_

I have got this installed now and running perfect but I can't figure out how to configure or change settings. For example change EXP lost on death. Could somehow let me know how this is done.

**Comment by Kaltharos** [comment]
Shutdown your server,
Go into the "BepInEx/config" folder,
Look for RPGMods.cfg

Make your changes in there, save the cfg, and start your server.
