### ISSUE TITLE
PvP Punishment not being applied.

### ISSUE THREAD

**Issue by Armored-22** [Kaltharos/RPGMods#23]
```
Enable PvP Punishment = true
Punish Level Difference = -10
Offense Limit = 1
Offense Cooldown = 300
Debuff Duration = 1800
```

When a level 75 kills a level 30 the level 75 does not receive the debuff values. The debuff can be applied manually with code. Does this have something to do with the 'Offense Limit' being 1?

**Comment by ImClieo** [comment]
Did you figure out what the issue here was? I'm having the same problem as.
