### ISSUE TITLE
Spawning to Waypoints

### ISSUE THREAD

**Issue by Armored-22** [Kaltharos/RPGMods#29]
After creating a waypoint 'arena' the bellow command does not work;

`.spawnnpc CHAR_Cursed_MountainBeast_VBlood 1 arena`

This does allow for waypoint spawning;

`spawnnpc CHAR_Cursed_MountainBeast_VBlood [1] arena`

However changing the spawn amount does not work. This is the only way I was able to spawn a NPC at a created waypoint.

**Comment by Kaltharos** [comment]
thanks!
will be fixed on next patch release
