### ISSUE TITLE
Not sure if it's working.

### ISSUE THREAD

**Issue by Tidgem** [Kaltharos/RPGMods#3]
So I logged in and my power had gone from 42 to 24, then I killed something and it went to 1. 

Its now at 3 after a few kills so I'm assuming that's me levelling? Could you add an XP bar or any kind of interface/UI at all so I know what's going on/what strength the levels are giving me?

**Comment by Kaltharos** [comment]
The levels are basically gear level being replaced, what the exp level give you is exactly what the gear level will give you equal to what that gear level will give you.

For experience, you can check with .experience or .xp

**Comment by Tidgem** [comment]
That all works awesomely thank you man. Would you consider adding an XP bar? I think it would really tie it all together :) Thanks again for the cool mod though and great work.

**Comment by Kaltharos** [comment]
XP bar will require a client side UI mod, it's an area i do not understand yet, hahaha

**Comment by Tidgem** [comment]
Ahh okay fair enough! well either way I've got the commands working now and am enjoying the bonuses immensely. However I changed the limit of waypoints to 30 yet am still unable to set more than 3. Is there some kind of admin override or something I need to edit? I believe all the other options change when I change them (Increased XP gain and V Blood kill XP for example both seem to be working fine). I'd just love complete waypoint freedom. What's the maximum and how do I override the default value? :) Thanks again!

**Comment by Tidgem** [comment]
Oh and maybe the server could autoping your XP occasionally? I imagine itd be easier than a UI bar but still provide an idea of how close you are to the next level. And would the option to change the level format from x/total xp to x/needed to level up?

**Comment by Kaltharos** [comment]
The waypoint sounds like a bug, I'll take a look at it.

For experience, use the .experience command, it's available to see there.
Have you read the mod information on the readme yet?

**Comment by Tidgem** [comment]
Yeah I knew how to check it I'm suggesting it auto-pings it occasionally to show the player without having to check themselves.

**Comment by Tidgem** [comment]
I'm not trying to rush/pester you, but did you get a chance to look at the waypoints bug yet? If not obviously that's fine I was just wondering :) Do you know when it might be fixed? I just really like the feature but the limit is too low for singleplayer :P

**Comment by Tidgem** [comment]
Awesome works now :) Thanks man. Time to try and find the upper limit of the waypoints by placing one at every Vblood and camp :D
