### ISSUE TITLE
Feature Suggestion: .nocooldown [playername]

### ISSUE THREAD

**Issue by BorgoMadonno** [Kaltharos/RPGMods#7]
Hi, is it possible to add that parameter? I want to disable a player cooldown as reward after some events.

**Comment by Kaltharos** [comment]
yes it's possible, however you need to keep track of them yourself.
Also, no cooldown for an event reward is too OP in my opinion...
But I'll try to sneak it into the next patch/update

**Comment by BorgoMadonno** [comment]
Yeah ofc, I meant give them nocooldown for like short period of time before disable it.
Thanks anyway.
